//! Minimal, read-only reader for the few `[Core.System]` fields that are
//! useful as layout evidence. Nothing read here changes resolution: the values
//! are reported next to the indexed layout so precedence questions can be
//! investigated with data. No other configuration is interpreted or executed.

use std::fs;
use std::io::Read;
use std::path::Path;

/// Upper bound on the bytes read from one ini file.
pub const MAX_INI_BYTES: u64 = 1 << 20;

/// Ini files (lowercase names) looked up in each code-root directory.
/// `Default.ini` ships with both installs; `XIII.ini` is generated by the game
/// on first run (present in the Steam copy only).
pub const INI_FILE_NAMES: &[&str] = &["default.ini", "xiii.ini"];

/// Raw `[Core.System]` values from one ini file.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CoreSystemFields {
    /// `Paths=` values in file order (commented lines excluded).
    pub paths: Vec<String>,
    /// `SpecificPackage=` values in file order.
    pub specific_packages: Vec<String>,
    /// `PlateForm=` value, if present.
    pub plateform: Option<String>,
}

/// One `Paths=` entry compared with the indexed layout.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IniPathCheck {
    /// Value as written, for example `..\Maps\BaseSP\*.unr`.
    pub raw: String,
    /// Directory relative to the installation root, lowercase and
    /// `/`-separated, or `None` if it escapes the root or cannot be parsed.
    pub resolved_dir: Option<String>,
    /// Lowercase extension of the wildcard pattern (for example `unr`).
    pub extension: Option<String>,
    /// Whether that directory exists in the walked inventory.
    pub dir_exists: bool,
    /// Whether that directory is an active search root of this installation.
    pub is_search_root: bool,
}

/// Evidence extracted from one ini file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IniEvidence {
    /// File path relative to the root (exact spelling).
    pub file: String,
    pub fields: CoreSystemFields,
    pub path_checks: Vec<IniPathCheck>,
    /// Active search roots (logical names) not covered by any `Paths=` entry.
    pub search_roots_not_in_paths: Vec<String>,
}

/// Where a `SpecificPackage=` name was found in the index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpecificPackageCheck {
    pub name: String,
    /// Relative paths of indexed packages with that logical name.
    pub found: Vec<String>,
}

/// Parses `[Core.System]` from ini text. Section and key names are matched
/// case-insensitively; lines starting with `;` are comments.
pub fn parse_core_system(text: &str) -> CoreSystemFields {
    let mut out = CoreSystemFields::default();
    let mut in_section = false;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with(';') {
            continue;
        }
        if let Some(rest) = line.strip_prefix('[') {
            in_section = rest
                .strip_suffix(']')
                .is_some_and(|s| s.trim().eq_ignore_ascii_case("core.system"));
            continue;
        }
        if !in_section {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let (key, value) = (key.trim(), value.trim().to_owned());
        if key.eq_ignore_ascii_case("paths") {
            out.paths.push(value);
        } else if key.eq_ignore_ascii_case("specificpackage") {
            out.specific_packages.push(value);
        } else if key.eq_ignore_ascii_case("plateform") {
            out.plateform = Some(value);
        }
    }
    out
}

/// Resolves a `Paths=` value written relative to `code_dir` (the lowercase
/// relative directory holding the ini, for example `system`) to a lowercase
/// directory relative to the installation root plus the pattern extension.
pub fn resolve_ini_path(code_dir: &str, raw: &str) -> (Option<String>, Option<String>) {
    let parts: Vec<&str> = raw
        .split(['\\', '/'])
        .filter(|p| !p.is_empty() && *p != ".")
        .collect();
    let Some((pattern, dirs)) = parts.split_last() else {
        return (None, None);
    };
    let extension = pattern
        .strip_prefix("*.")
        .map(str::to_ascii_lowercase)
        .filter(|e| !e.is_empty() && !e.contains(['*', '?']));
    let mut stack: Vec<String> = code_dir
        .split('/')
        .filter(|p| !p.is_empty())
        .map(str::to_owned)
        .collect();
    for d in dirs {
        if *d == ".." {
            if stack.pop().is_none() {
                return (None, extension);
            }
        } else if d.contains(':') {
            return (None, extension);
        } else {
            stack.push(d.to_ascii_lowercase());
        }
    }
    (Some(stack.join("/")), extension)
}

/// Reads at most [`MAX_INI_BYTES`] of an ini file as (lossy) text.
pub(crate) fn read_bounded(path: &Path) -> std::io::Result<String> {
    let mut buf = Vec::new();
    fs::File::open(path)?
        .take(MAX_INI_BYTES)
        .read_to_end(&mut buf)?;
    Ok(String::from_utf8_lossy(&buf).into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "[URL]\nPaths=ignored\n[Core.System]\r\nSavePath=..\\Save\r\n\
        Paths=..\\System\\*.u\r\nPaths=..\\Maps\\*.unr\r\n;;;Paths=..\\StaticMeshes\\*.usx\r\n\
        PlateForm=0\r\nSpecificPackage=XIIIPersos.u\r\nspecificpackage = GUI.u\r\n\
        [Engine.GameEngine]\r\nPaths=..\\Other\\*.u\r\n";

    #[test]
    fn parses_only_core_system_and_skips_comments() {
        let f = parse_core_system(SAMPLE);
        assert_eq!(f.paths, ["..\\System\\*.u", "..\\Maps\\*.unr"]);
        assert_eq!(f.specific_packages, ["XIIIPersos.u", "GUI.u"]);
        assert_eq!(f.plateform.as_deref(), Some("0"));
    }

    #[test]
    fn resolves_relative_paths() {
        assert_eq!(
            resolve_ini_path("system", "..\\Maps\\BaseSP\\*.unr"),
            (Some("maps/basesp".into()), Some("unr".into()))
        );
        assert_eq!(
            resolve_ini_path("system", "..\\System\\*.u"),
            (Some("system".into()), Some("u".into()))
        );
        assert_eq!(resolve_ini_path("system", "..\\..\\Outside\\*.u").0, None);
        assert_eq!(resolve_ini_path("system", "C:\\Games\\*.u").0, None);
        assert_eq!(resolve_ini_path("system", "").0, None);
    }
}
