[package]
name = "xiii-app"
description = "Bevy runtime for XIII Classic content imported from an owned installation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true }
xiii-package.workspace = true
xiii-install.workspace = true
xiii-decode.workspace = true
xiii-script.workspace = true
xiii-collision.workspace = true
xiii-audio.workspace = true
xiii-world.workspace = true
xiii-video.workspace = true

[lints]
workspace = true
